FROM jwilder/nginx-proxy:latest

# COPY ./nginx.tmpl /app/nginx.tmpl
COPY ./html/custom_pages/503.html /usr/share/nginx/html/503.html
COPY ./html/custom_pages/502.html /usr/share/nginx/html/502.html